config/routes.rb
PiMiner::Application.routes.draw do
  root :to => 'home#index'
  get 'chart', to: 'home#chart'
  get 'overview', to: 'home#overview'
  get 'devices', to: 'home#devices'
  get 'pools', to: 'home#pools'

  # Device management
  match '/device/:id', to: 'device#show', as: 'show_device'
  match '/device/:id/disable', to: 'device#disable', as: 'disable_device'
  match '/device/:id/enable', to: 'device#enable', as: 'enable_device'

  # Pool management
  match '/pool/:id/disable', to: 'pool#disable', as: 'disable_pool'
  match '/pool/:id/enable', to: 'pool#enable', as: 'enable_pool'
  match '/pool/:id/delete', to: 'pool#delete', as: 'delete_pool'
  match '/pool/new', to: 'pool#new', as: 'new_pool'
  match '/pool/create', to: 'pool#create', as: 'create_pool'
  match '/pool/:id/update', to: 'pool#update', as: 'update_pool'
end

app/models/api.rb
$api_host = '192.168.0.6'
$api_port = 4028

class Api # A very simple api wrapper that caches results
  require 'socket'
  require 'json'

  attr_accessor :port, :host

  def self.create
    @@inst ||= Api.new($api_host, $api_port)
  end

  def privileged?
    self.privileged[:status] != :error
  end

  def initialize(host='localhost', port=4028)
    @host, @port = host, port
  end

  def query(method, *params)
    req = {command: method}
    unless params.length == 0
      params = params.map { |p| p.to_s.gsub('\\', '\\\\').gsub(',', '\,') }
      req[:parameter] = params.join(',')
    end
    req = req.to_json

    s = TCPSocket.open(@host, @port)
    s.write req
    data = s.read.strip
    # Okay, nasty, can have control character.... let's strip 'em!
    data = data.chars.map { |c| c.ord >= 32 ? c : "\\u#{'%04x' % c.ord}" }.join
    data = JSON.parse(data)
    s.close

    # Check status
    status = data['STATUS'][0]
    sc = status['STATUS']
    c = status['Code']
    msg = status['Msg']
    data.delete('STATUS')
    case sc
      when 'S'
      when 'I'
        logger.info "Info from API [#{c}]: #{msg}"
      when 'W'
        logger.info "Warning from API [#{c}]: #{msg}"
      else
        raise "#{sc}: #{msg}"
    end

    data = sanitise(data)
    return {status: :ok, code: c, message: msg, data: data}
  end

  def method_missing(name, *args)
    query(name, *args)
  end

  def version
    query('version')[:data][:version][0]
  end

  def summary
    query('summary')[:data][:summary][0]
  end

  def pools
    query('pools')[:data][:pools].each do |pool|
      pool[:status] = pool[:status].downcase.to_sym
    end
  end

  def pool(id)
    pools.keep_if { |e| e[:id] == id }.first
  end

  def update_pool(pool)
    addpool(pool[:url], pool[:user], pool[:pass]) # Add the new one
    pools = self.pools
    new = pools.last
    new[:priority] = pools[pool[:id]][:priority] # Set priorities
    pools[pool[:id]][:priority] = pools.length + 5
    order = pools.sort { |a, b| a[:priority] <=> b[:priority] }.map { |p| p[:pool] }
    poolpriority(*order) # Change pool priorities
    removepool(pool[:id]) # Remove the old pool
  end

  def devices
    devs = query 'devs'
    mapped = devs[:data][:devs].map do |dev|
      dev[:enabled] = dev[:enabled] == true || dev[:enabled] == 'Y'
      dev[:status] = dev[:status].downcase.to_sym
      types = [:cpu, :gpu, :pga, :asc]
      types.each do |type|
        next unless dev.has_key?(type)
        raise 'Device with multiple types' if dev.has_key?(:type)
        dev[:type] = type
      end
      dev
    end
    mapped
  end

  def device(id)
    devices.keep_if { |e| e[:id] == id }.first
  end

  def enable_device(id)
    type = device(id)[:type]
    case type
      when :gpu then
        gpuenable(id)
      when :pga then
        pgaenable(id)
      when :asc then
        ascenable(id)
      else
        raise "I don't know how to enable devices of type #{type}"
    end
  end

  def disable_device(id)
    type = device(id)[:type]
    case type
      when :gpu then
        gpudisable(id)
      when :pga then
        pgadisable(id)
      when :asc then
        ascdisable(id)
      else
        raise "I don't know how to disable devices of type #{type}"
    end
  end

  private
  def sanitise(data)
    if data.is_a?(Hash)
      data.inject({}) { |n, (k, v)| n[k.downcase.gsub(' ', '_').to_sym] = sanitise(v); n }
    elsif data.is_a?(Array)
      data.map { |v| sanitise(v) }
    else
      data
    end
  end
end

app/models/data_point.rb
class DataPoint
  DataPointKey = 'hash_data'

  def self.range(start, finish)
    $redis.zrangebyscore(DataPointKey, start.to_i, finish.to_i, with_scores: true).map { |a| {time: a[1].to_i, value: a[0].to_f} }
  end

  def self.add(date, value)
    $redis.zadd(DataPointKey, date.to_i, value)
    $redis.zremrangebyscore(DataPointKey, 0, 1.year.ago.to_i)
    # Todo: better cleanup here
    # Aggregate older items into averages, etc.
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :init

  helper_method :app_name, :app_version, :elapsed_time, :mhash_to_s, :miner, :privileged?, :json_protect

  def init
    @start_time = Time.now
  end

  def app_name
    "PiMiner"
  end

  def app_version
    "0.1a"
  end

  def elapsed_time
    Time.now - @start_time
  end

  def mhash_to_s(speed)
    units = %w(M G T P)
    unit = 0
    while speed > 1000
      speed = speed.to_f / 1000.0
      unit += 1
    end
    "#{speed.round(2)} #{units[unit]}h/s"
  end

  def miner
    @miner ||= Api.create
  end

  def json_protect
    begin
      render json: {status: :ok, result: yield}
    rescue Exception => e
      render json: {status: :err, message: e.to_s}, status: 500
    end
  end

  # Todo: login system
  def privileged?
    true && miner.privileged?
  end
end

app/controllers/device_controller.rb
class DeviceController < ApplicationController
  def show
    json_protect do
      miner.device(params[:id].to_i)
    end
  end

  def disable
    json_protect do
      miner.disable_device(params[:id].to_i)
      nil
    end
  end

  def enable
    json_protect do
      miner.enable_device(params[:id].to_i)
      nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include ActionView::Helpers::DateHelper

  def index
  end

  def chart
    @start = Time.at(params[:start].to_i).to_datetime
    @interval = params[:interval].to_i
    render json: {
        title: @title,
        start: @start.to_i*1000,
        data: get_data(@start, @interval)
    }
  end

  def overview
    @devs = miner.devices
    unless @devs.empty?
      @sum = miner.summary
      @speed = mhash_to_s(@devs.map { |dev| dev[:mhs_5s] }.reduce(:+))
    end
    render layout: false
  end

  def devices
    # Get device json data
    miner.devices
    @devs = miner.devices
    render layout: false, partial: 'devices'
  end

  def pools
    @pools = miner.pools
    miner.summary
    render layout: false, partial: 'pools'
  end

  private
  def get_data(start_date, interval)
    # Select the data within range
    start = start_date.to_i
    start -= start % interval
    fin = DateTime.now.to_i
    fin -= fin % interval
    endy = Time.at(fin).to_datetime
    interval = interval.to_f
    data = DataPoint.range(Time.at(start).to_datetime, endy)

    elapsed = endy.to_i - start
    groups = Array.new(elapsed / interval.to_i) { [] }

    # Group the data by our interval
    data.each do |dp|
      utime = dp[:time] - start
      idx = (utime.to_f / interval).floor
      groups[idx-1] << dp[:value]
    end

    # Average and return as time, value pairs
    groups.map do |arr|
      arr.empty? ? 0 : arr.reduce(:+) / arr.length
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/device_helper.rb
module DeviceHelper
end

app/helpers/home_helper.rb
module HomeHelper

end

app/views/home/_devices.html.haml
-names = ['Accepted', 'Rejected', 'Hardware errors']
- @devs ||= []
.panel
  %h3.panel-heading
    %i.icon-hdd
    Devices
    %small.text-muted#devices_overview
      - unless @devs.empty?
        = pluralize(@devs.length, 'device')
        %span{style: 'font-size: 0.8em'}
          -types = [[:cpu, 'CPU'], [:gpu, 'GPU'], [:pga, 'FPGA']].map{|a| count = @devs.count{|d| d[:type] == a[0]};count == 0? nil: pluralize(count,a[1])}.compact.join(', ')
          ="(#{types})"
  %table.table.table-striped
    %thead
      %tr
        %th Name
        %th Type
        %th Status
        %th Temp
        %th{title: '5 second average'} Mh/s
        %th=names.join('/')
        %th Utility
    %tbody
      -if @devs.length == 0
        %tr
          %td{colspan:7}
            .text-center No device information available
      -else
        -@devs.each do |dev|
          -status = dev[:enabled]? dev[:status].downcase.to_sym: :disabled
          %tr{class:  status == :alive ? :success: status == :disabled ? :warning: :danger}
            %td=dev[:name]
            %td=dev[:type].to_s.titleize
            %td
              -if dev[:type] != :cpu && privileged?
                =link_to(status == :disabled ? enable_device_path(dev[:id]): disable_device_path(dev[:id]), remote: true) do
                  %i{class: "icon-check#{status == :disabled ? '-empty': ''}", title: status == :disabled ? 'Enable device': 'Disable device'}
              =status.to_s.titleize
            %td= dev[:temperature].nil?? 'N/A': dev[:temperature].round(2)
            %td=mhash_to_s(dev[:mhs_5s])
            %td
              :ruby
                keys = [:accepted, :rejected, :hardware_errors]
                classes = %w(success warning danger)
                vals = keys.map{|k| dev[k]}
                total = vals.reduce(:+)
                perc = keys.map{|k| total == 0? 0: (dev[k].to_f / total.to_f) * 100.0}
              .progress{style: 'margin-bottom:0'}
                - keys.each_with_index do |key,index|
                  - val = dev[key]
                  .progress-bar{style:"width: #{perc[index].round(2)}%", title: "#{names[index]}: #{val} (#{perc[index].round(2)}%)", class: "progress-bar-#{classes[index]}"}
            %td=dev[:utility]

app/views/home/_hashchart.html.haml
.span12
  :javascript
      $(function(){
          Highcharts.setOptions({global:{useUTC: false}});
          chart = new Highcharts.Chart({
            chart: {
              renderTo: 'hashchart'
            }, title: {
              text: ""
            }, xAxis: {
              type: "datetime",
              ordinal: true
            }, yAxis: {
              min: 0,
              title: {
                text: 'MHash/s'
              }
            }, legend: {
              enabled: false
            }, tooltip: {
              formatter: function() {
                var val = this.y;
                var pres = ['M', 'G', 'T', 'P'];
                var pre = 0;
                while(val > 1000) {
                  pre++;
                  val = val / 1000.0;
                }
                val = val.toFixed(2);
                return Highcharts.dateFormat("%B %e %Y %H:%M", this.x) + ', <b>' + val + pres[pre] + 'hash/s';
              }
            }, exporting: {
              enabled: true
            }, plotOptions: {
                   line: {
                       marker: {
                           enabled: false
                       }
                   }
               }
          });
          chart.showLoading();
      });
  .chart{id: 'hashchart'}

app/views/home/_pools.html.haml
-names = ['Accepted', 'Rejected', 'Stale', 'Discarded']
- @pools ||= []
- @pools.sort! {|a,b| a[:priority] <=> b[:priority]}
.panel
  %h3.panel-heading
    %i.icon-globe
    Pools
    %small.text-muted#devices_overview
      - unless @pools.empty?
        =pluralize(@pools.length, 'pool')
  %table.table.table-striped
    %thead
      %tr
        %th Priority
        %th URL
        %th User
        %th Status
        %th=names.join('/')
        - if privileged?
          %th.text-center Options
    %tbody
      -if @pools.length == 0
        %tr
          %td{colspan:6}
            .text-center No pool information available
      -else
        -@pools.each do |pool|
          %tr{class: pool[:status] == :alive ? :success: pool[:status] == :disabled ? :warning: :danger, id: "pool#{pool[:pool]}"}
            %td
              =pool[:priority]
              -if privileged?
                %span.priority-change{style: 'position: relative'}
                  %a.pri-up{class: pool[:priority] == 0 ? 'disabled': ''}<>
                    %i.icon-angle-up
                  %a.pri-down{class: pool[:priority] == @pools.length - 1? 'disabled': ''}<>
                    %i.icon-angle-down

            %td{id: "pool#{pool[:pool]}_url"}=pool[:url]
            %td{id: "pool#{pool[:pool]}_user"}=pool[:user]
            %td=pool[:status].to_s.titleize
            %td
              :ruby
                keys = [:accepted, :rejected, :stale, :discarded]
                classes = %w(success warning warning danger)
                vals = keys.map{|k| pool[k]}
                total = vals.reduce(:+)
                perc = vals.map{|v| (v.to_f/total) * 100.0}
              .progress{style: 'margin-bottom: 0'}
                - keys.each_with_index do |key,index|
                  .progress-bar{style:"width: #{perc[index].round(2)}%", title: "#{names[index]}: #{vals[index]} (#{perc[index].round(2)}%)", class: "progress-bar-#{classes[index]}"}
            - if privileged?
              %td.text-center
                %span.option-link
                  =link_to(pool[:status] == :disabled ? enable_pool_path(pool[:pool]): disable_pool_path(pool[:pool]), remote: true, data: {refresh: 'pools'}) do
                    %i{class: "icon-check#{pool[:status] == :disabled ? '-empty': ''}", title: pool[:status] == :disabled ? 'Enable pool': 'Disable pool'}<>
                %span.option-link
                  =link_to(update_pool_path(pool[:pool]), onclick: 'return false', data: {poolEdit: pool[:pool]}) do
                    %span{title: 'Settings'}<>
                      %i.icon-wrench
                %span.option-link
                  =link_to(delete_pool_path(pool[:pool]), remote: true, data: {confirm: 'Are you sure you want to delete this pool?', refresh: 'pools'}) do
                    %span{title: 'Delete'}<>
                      %i.icon-trash
  -if privileged?
    =link_to(new_pool_path, id: 'new_pool', class: 'btn btn-primary', data: {toggle: 'modal', target: '#pool_settings'}, onclick: 'return false') do
      %i.icon-plus
      Add pool
    %script
      $('#new_pool').attr('href', $('#new_pool').data('target'));

app/views/home/index.html.haml
.row.text-center#chart_container
  .panel
    .panel-heading
      .row
        .col-lg-2
          %h3.text-left.panel-title{style: 'font-size:26px'}
            %i.icon-bar-chart
            Charts
        / Chart selection
        -day = 60*60*24
        - time = {minutes: 60, hours: 60*60, days: day, weeks: day*7, months: day*28, years: day*365}
        .col-lg-4.col-offset-2.col-lg-offset-2.col-sm-5.col-sm-offset-2
          %form.form-horizontal
            %label.col-lg-3.col-sm-3.control-label Range:
            .col-lg-4.col-sm-4
              =select('range_value', 'select', 1...30, {}, class: 'form-control input-small')
            .col-lg-5.col-sm-5
              =select('range_unit', 'select', time, {}, class: 'form-control input-small')
        .col-lg-4.col-sm-5
          %form.form-horizontal
            %label.col-lg-3.col-sm-3.control-label Interval:
            .col-lg-4.col-sm-4
              =select('interval_value', 'select', 1...30, {}, class: 'col-lg-4 form-control input-small')
            .col-lg-5.col-sm-5
              =select('interval_unit', 'select', time, {}, class: 'col-lg-5 form-control input-small')
    #chart_panel_content
      = render partial: 'hashchart'
    :javascript
      // Some stuff for the rest of our js
      rangevalsel = $('#range_value_select')
      rangeunsel = $('#range_unit_select')
      intvalsel = $('#interval_value_select')
      intunsel = $('#interval_unit_select')
.row#device_container
  =render partial: 'devices'


.modal.fade#pool_settings
  .modal-dialog
    .modal-content
      .modal-header
        %h4
          %i.icon-globe
          Pool settings
          %button.close{'data-dismiss' => 'modal', 'aria-hidden' => true} &times;
      .modal-body
        .form-group
          %input#pool_editmode{type: :hidden, value: 'unknown'}
          %label{for: :pool_url} Pool URL
          %input#pool_url.form-control{placeholder: 'Enter URL'}
          %p.help-block Format &lt;host&gt;:&lt;port&gt; e.g. pool.50btc.com:8332
          %label{for: :pool_user} Worker username
          %input#pool_user.form-control{placeholder: 'Enter username'}
          %label{for: :pool_pass} Worker password
          %input#pool_pass.form-control{placeholder: 'Enter password'}
      .modal-footer
        %button.btn.btn-primary#save_pool{'data-dismiss' => 'modal'} Save
        %button.btn.btn-default{'data-dismiss' => 'modal'} Close
.row#pool_container
  =render partial: 'pools'

app/views/home/overview.html.haml
- unless @devs.empty?
  %span.pad-horizontal
    %i.icon-time
    Uptime:
    =time_ago_in_words(Time.now.to_i - @sum[:elapsed])
  |
  %span.pad-horizontal
    %i.icon-signal
    Speed:
    =@speed

app/views/layouts/application.html.haml
!!!
%html{lang: :en}
  %head
    %title=app_name
    =stylesheet_link_tag 'application', media: :all
    =javascript_include_tag 'application', params[:controller]
    =csrf_meta_tags
  %body
    .navbar.navbar-fixed-top
      .container
        %a.navbar-brand=app_name
        %button.navbar-toggle{:'data-toggle' => :collapse, :'data-target' => '.navbar-responsive-collapse'}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        .nav-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li.active
              %a{href: '#'} Home
          %ul.nav.navbar-nav.pull-right
            %li.dropdown
              %a.dropdown-toggle#alert-drop{href: '#', 'data-toggle' => 'dropdown'}
                %i.icon-bell-alt
                Alerts
                %span.badge#alert_count
                %b.caret
              %ul.dropdown-menu#alert-dropdown{role: :menu, 'aria-labelledby' => '#alert-drop'}
                %li
                  .text-center.text-muted#no_alerts No new alerts
        .navbar-text.text-right#overview
    .container
      .modal.fade#alert_modal
        .modal-dialog
          .modal-content.alert
            .modal-header
              %h4
                %i.icon-bell-alt
                %span#alert-title
                  Alert
                %button.close{'data-dismiss' => 'modal', 'aria-hidden' => true} &times;
            .modal-body#alert_container
            .modal-footer
              / Todo: previous, next, dismiss
      =yield
    .modal.fade#message-modal
      .modal-dialog
        .modal-content
          .modal-header
            %h4
              %i#message-icon.icon-info-sign
              %span#message-title
                Message
              %button.close{'data-dismiss' => 'modal', 'data-target' => '#message-modal', 'aria-hidden' => true} &times;
          .modal-body#message
          .modal-footer
            %button#message-ok.btn.btn-primary{'data-dismiss' => 'modal', 'aria-hidden' => true} Ok
            %button#message-cancel.btn.btn-default{'data-dismiss' => 'modal', 'aria-hidden' => true} Cancel

    .modal.fade#progress_modal
      .modal-dialog
        .modal-content
          .modal-header
            %h4
              %i.icon-cogs
              %span#wait-message
                Please wait...
          .modal-body
            .progress.progress-striped.active
              .progress-bar{style: 'width: 100%'}
                %span#wait-message
                  Please wait...

    .modal.fade#donate_modal
      .modal-dialog
        .modal-content
          .modal-header
            %h4
              %i.icon-btc
              Donate
              %button.close{'data-dismiss' => 'modal', 'aria-hidden' => true} &times;
          .modal-body
            .text-info
              All donations will go towards development of applications relating to bitcoin such as this and a few other
              projects I have under development.  Thanks!
            %br
            .input-group
              %span.input-group-addon{onclick: "$('#donate_address').select()", style: 'cursor: pointer'}
                %i.icon-btc
              %input.form-control#donate_address{type: :text, value: '17UQa8vbadrw6NzqZfbgi2WdQDHqjWma7N', onclick: "$('#donate_address').select()", readonly: :readonly, style: 'cursor:pointer'}
          .modal-footer
            %button.btn.btn-default{'data-dismiss' => 'modal'} Close

    %footer
      .container
        .row.text-center
          =app_name
          is free software created by James Lawrence in his spare time.  If you like it,
          %a{'data-toggle' => 'modal', href: '#donate_modal'}
            %i.icon-btc
            donate
        .row.text-center
          =link_to('#email' ,class: 'pad-horizontal') do
            %i.icon-envelope
            Message Me
          |
          =link_to('#linkedin', class: 'pad-horizontal') do
            %i.icon-briefcase
            Hire Me
          |
          =link_to('#sqrt4', class: 'pad-horizontal') do
            %i.icon-eye-open
            Peruse Me
          |
          = link_to('#github', class: 'pad-horizontal') do
            %i.icon-github
            Fork Me
        .row.text-center
          %small
            Page rendered in
            =elapsed_time
            seconds. |

            Powered by
            =request.headers['SERVER_SOFTWARE']
        - if !Rails.env.production? && false # Set to true to enable env and header dump
          %h2.text-center Variable debugging (disable in application.html.haml)
          -[['Environment', ENV], ['Headers', request.headers]].each do |name,hash|
            %h4.text-center=name
            %dl.dl-horizontal
              -hash.each do |k,v|
                %dt{title: k}=k
                %dd=v